using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using OperaLegacyLab.Web.Infrastructure;
using OperaLegacyLab.Web.Services;
using System.Net;

// `dotnet watch run` (and Visual Studio's equivalent hot-reload launch) auto-injects
// Microsoft.AspNetCore.Watch.BrowserRefresh via the ASPNETCORE_HOSTINGSTARTUPASSEMBLIES env var - it
// wraps the ENTIRE response pipeline (as an IHostingStartup/IStartupFilter, outside even this app's
// own PageSizeReportMiddleware) and tacks a <script src="/_framework/aspnetcore-browser-refresh.js">
// onto every plain HTML response. That's unwanted extra bytes over the wire for a project whose whole
// point is exact control over what's actually sent to a 2005-era phone browser - confirmed by
// deliberately re-enabling it and diffing the response before/after. Setting
// DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH=1 works, but only when set on dotnet-watch's OWN process
// before it starts (the env var lives in launchSettings.json applies too late - it only reaches the
// spawned app, after dotnet-watch has already decided whether to add the hosting startup assembly).
// Stripping the assembly out of the variable here instead - as the very first thing this program
// does, before WebApplication.CreateBuilder(args) reads it - disables just this one feature reliably
// regardless of how the app is launched (dotnet run, dotnet watch run, F5 in Visual Studio), with no
// reliance on every developer remembering to set anything themselves.
var hostingStartupAssemblies = Environment.GetEnvironmentVariable("ASPNETCORE_HOSTINGSTARTUPASSEMBLIES");
if (!string.IsNullOrEmpty(hostingStartupAssemblies))
{
    var withoutBrowserRefresh = hostingStartupAssemblies
        .Split(';', StringSplitOptions.RemoveEmptyEntries)
        .Where(a => !a.Contains("BrowserRefresh", StringComparison.OrdinalIgnoreCase));
    Environment.SetEnvironmentVariable("ASPNETCORE_HOSTINGSTARTUPASSEMBLIES", string.Join(';', withoutBrowserRefresh));
}

var builder = WebApplication.CreateBuilder(args);

// Nokia 9300 / Opera 6.x era browsers speak plain HTTP/1.1 - no HTTP/2. TLS 1.2
// works on the phone (confirmed via a device-side patch), reached exclusively
// through a public tunnel (ngrok, Cloudflare Tunnel/cloudflared, or similar) -
// the phone can't reach this app over the LAN. Whichever tunnel is in use
// terminates the REAL TLS connection with the phone at its own public edge;
// this app's own local listeners are just the tunnel daemon's origin backend,
// and the phone never sees or cares about either one's certificate (or lack
// of one) - only the tunnel's own public cert matters to the phone.
//
// Point your tunnel at whichever of these two local listeners it can actually
// reach with the trust it has:
//   - http origin (LabPort, default 5000): no certificate involved at all on
//     this hop - the tunnel decrypts its own public HTTPS at its edge and
//     forwards plain HTTP locally. This is the common, simplest setup (ngrok's
//     and cloudflared's own quickstarts both default to exactly this) and is
//     equally secure from the phone's point of view either way - point your
//     tunnel command at http://localhost:<LabPort> and nothing further is
//     needed.
//   - https origin (LabHttpsPort, default 5253): only useful if you want the
//     tunnel-daemon-to-Kestrel hop itself encrypted/verified too. Kestrel
//     serves this with the ASP.NET Core HTTPS DEVELOPMENT certificate (the
//     same one `dotnet dev-certs https` manages) rather than a one-off
//     self-signed cert generated by this project, specifically because a
//     tunnel client that verifies certificates (cloudflared does, by default,
//     unlike ngrok) needs to actually trust it - which `dotnet dev-certs
//     https --trust` (run once, locally) sets up for you via the normal OS
//     trust store, rather than this project inventing its own untrusted one
//     that a verifying client would always reject.
//
// Bind explicitly to all network interfaces (not just localhost) so the
// tunnel daemon (or anything else on this machine) can reach either listener.
var port = builder.Configuration.GetValue<int?>("LabPort") ?? 5000;
var httpsPort = builder.Configuration.GetValue<int?>("LabHttpsPort") ?? 5253;

builder.WebHost.ConfigureKestrel(options =>
{
    options.Listen(IPAddress.Any, port, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1;
    });

    options.Listen(IPAddress.Any, httpsPort, listenOptions =>
    {
        listenOptions.Protocols = HttpProtocols.Http1;
        // No certificate argument: Kestrel resolves this to the ASP.NET Core
        // HTTPS development certificate automatically (see the comment block
        // above) - run `dotnet dev-certs https --trust` once locally if you
        // want a certificate-verifying tunnel client to accept this listener.
        listenOptions.UseHttps();
    });

    // Old/slow mobile links can take a long time to send or receive a request -
    // don't let Kestrel's default minimum-data-rate watchdogs kill those
    // connections early.
    options.Limits.MinRequestBodyDataRate = null;
    options.Limits.MinResponseDataRate = null;
    options.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(5);
    options.Limits.RequestHeadersTimeout = TimeSpan.FromMinutes(2);
});

builder.Services.AddSingleton<LabSessionStore>();
builder.Services.AddSingleton<DeviceResultLog>();
builder.Services.AddRazorPages();
builder.Services.AddHttpClient("uaprof", client =>
{
    client.Timeout = TimeSpan.FromSeconds(5);
    client.DefaultRequestHeaders.UserAgent.ParseAdd("OperaLegacyLab/1.0 (+capability-test-harness)");
});

var app = builder.Build();

// Force DeviceResultLog to construct now rather than lazily on the first
// request that needs it, so it reloads any results the device already gave
// us in a previous run (see DeviceResultLog's own doc comment - it now
// PRESERVES device-results.txt/.state.json across a restart, it doesn't
// clear them) as early as possible rather than only once the first test
// happens to run.
app.Services.GetRequiredService<DeviceResultLog>();

// Whichever tunnel is in front of this app (ngrok, cloudflared, or similar) terminates the real TLS
// connection with the phone and forwards to us over its own separate local connection (http or https
// depending on which listener you pointed it at) - without this, diagnostic pages could wrongly report
// "http" even though the phone connected over https. KnownNetworks/KnownProxies are cleared because the
// tunnel's edge IP can't be listed in advance; that's a deliberate relaxation appropriate for a
// throwaway diagnostic tool, not a pattern to copy into anything security-sensitive.
var forwardedHeaderOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
};
forwardedHeaderOptions.KnownIPNetworks.Clear();
forwardedHeaderOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardedHeaderOptions);

// Deliberately no app.UseHttpsRedirection() / no HSTS: what matters here is the tunnel's own https to
// the phone, not redirect behavior on this local hop (which may well be plain http - see the listener
// comment above).
app.UseStaticFiles();

// Buffers every response and, only for pages using the shared _Layout.cshtml, prepends a real
// page-size/compression report and (unlike anywhere else in this app) actually compresses the
// response when this request's own Accept-Encoding asked for gzip - see PageSizeReportMiddleware's
// own doc comment for why this is safe for the pages that deliberately bypass the shared layout for
// byte-exact testing (EncodingLatin1, WapWml, ReportText, /test/qr-png, every /test/compression/*).
app.UseMiddleware<PageSizeReportMiddleware>();

// Every route in this app - home page, every test, diagnostics, the report -
// is a Razor Page under Pages/, routed by convention/@page directive. This
// one call replaces what used to be a dozen separate app.MapXxxEndpoints()
// registrations.
app.MapRazorPages();


var gifPath = Path.Combine(
    app.Environment.WebRootPath,
    "images",
    "loading.gif");

if (!File.Exists(gifPath))
{
    LoadingGifGenerator.Generate(gifPath);
}

app.Run();
